CREATE TABLE classes (
	id_class	serial		PRIMARY KEY,
	label		varchar(2)	NOT NULL,
	asciiCode	integer		NOT NULL
);
COMMENT ON TABLE classes IS 'Classes of characters assumed in classification stage.';


CREATE TABLE samples (
	id_sample	serial	PRIMARY KEY,
	m00			numeric	NOT NULL DEFAULT 0.0,
	m10			numeric	NOT NULL DEFAULT 0.0,
	m01			numeric	NOT NULL DEFAULT 0.0,
	m11			numeric	NOT NULL DEFAULT 0.0,
	m20			numeric	NOT NULL DEFAULT 0.0,
	m02			numeric	NOT NULL DEFAULT 0.0,
	m21			numeric	NOT NULL DEFAULT 0.0,
	m12			numeric	NOT NULL DEFAULT 0.0,
	m22			numeric	NOT NULL DEFAULT 0.0,
	m30			numeric	NOT NULL DEFAULT 0.0,
	m03			numeric	NOT NULL DEFAULT 0.0,
	m31			numeric	NOT NULL DEFAULT 0.0,
	m13			numeric	NOT NULL DEFAULT 0.0,
	m32			numeric	NOT NULL DEFAULT 0.0,
	m23			numeric	NOT NULL DEFAULT 0.0,
	m33			numeric	NOT NULL DEFAULT 0.0,
	m40			numeric	NOT NULL DEFAULT 0.0,
	m04			numeric	NOT NULL DEFAULT 0.0,
	m41			numeric	NOT NULL DEFAULT 0.0,
	m14			numeric	NOT NULL DEFAULT 0.0,
	m42			numeric	NOT NULL DEFAULT 0.0,
	m24			numeric	NOT NULL DEFAULT 0.0,
	m43			numeric	NOT NULL DEFAULT 0.0,
	m34			numeric	NOT NULL DEFAULT 0.0,
	m44			numeric	NOT NULL DEFAULT 0.0,
	m50			numeric	NOT NULL DEFAULT 0.0,
	m05			numeric	NOT NULL DEFAULT 0.0,
	id_class	integer	REFERENCES classes
);
CREATE INDEX iClass ON samples(id_class);
COMMENT ON TABLE samples IS 'Feature vectors associated to a class of characters.';


-- Insert data
INSERT INTO classes (id_class, label, asciiCode) VALUES
	(DEFAULT, '0', 48),
	(DEFAULT, '1', 49),
	(DEFAULT, '2', 50),
	(DEFAULT, '3', 51),
	(DEFAULT, '4', 52),
	(DEFAULT, '5', 53),
	(DEFAULT, '6', 54),
	(DEFAULT, '7', 55),
	(DEFAULT, '8', 56),
	(DEFAULT, '9', 57),
	(DEFAULT, 'A', 65),
	(DEFAULT, 'B', 66),
	(DEFAULT, 'C', 67),
	(DEFAULT, 'D', 68),
	(DEFAULT, 'E', 69),
	(DEFAULT, 'F', 70),
	(DEFAULT, 'G', 71),
	(DEFAULT, 'H', 72),
	(DEFAULT, 'I', 73),
	(DEFAULT, 'J', 74),
	(DEFAULT, 'K', 75),
	(DEFAULT, 'L', 76),
	(DEFAULT, 'M', 77),
	(DEFAULT, 'N', 78),
	(DEFAULT, 'O', 79),
	(DEFAULT, 'P', 80),
	(DEFAULT, 'Q', 81),
	(DEFAULT, 'R', 82),
	(DEFAULT, 'S', 83),
	(DEFAULT, 'T', 84),
	(DEFAULT, 'U', 85),
	(DEFAULT, 'V', 86),
	(DEFAULT, 'W', 87),
	(DEFAULT, 'X', 88),
	(DEFAULT, 'Y', 89),
	(DEFAULT, 'Z', 90),
	(DEFAULT, 'a', 97),
	(DEFAULT, 'b', 98),
	(DEFAULT, 'c', 99),
	(DEFAULT, 'd', 100),
	(DEFAULT, 'e', 101),
	(DEFAULT, 'f', 102),
	(DEFAULT, 'g', 103),
	(DEFAULT, 'h', 104),
	(DEFAULT, 'i', 105),
	(DEFAULT, 'j', 106),
	(DEFAULT, 'k', 107),
	(DEFAULT, 'l', 108),
	(DEFAULT, 'm', 109),
	(DEFAULT, 'n', 110),
	(DEFAULT, 'o', 111),
	(DEFAULT, 'p', 112),
	(DEFAULT, 'q', 113),
	(DEFAULT, 'r', 114),
	(DEFAULT, 's', 115),
	(DEFAULT, 't', 116),
	(DEFAULT, 'u', 117),
	(DEFAULT, 'v', 118),
	(DEFAULT, 'w', 119),
	(DEFAULT, 'x', 120),
	(DEFAULT, 'y', 121),
	(DEFAULT, 'z', 122),
	(DEFAULT, 'Ñ', 209),
	(DEFAULT, 'Ç', 199),
	(DEFAULT, 'Á', 193),
	(DEFAULT, 'É', 201),
	(DEFAULT, 'Í', 205),
	(DEFAULT, 'Ó', 211),
	(DEFAULT, 'Ú', 218),
	(DEFAULT, 'Ü', 220),
	(DEFAULT, 'ñ', 241),
	(DEFAULT, 'á', 225),
	(DEFAULT, 'é', 233),
	(DEFAULT, 'í', 237),
	(DEFAULT, 'ó', 243),
	(DEFAULT, 'ú', 250),
	(DEFAULT, 'ü', 252),
	(DEFAULT, 'ç', 231),
	(DEFAULT, ' ', 32),
	(DEFAULT, '¡', 161),
	(DEFAULT, '!', 33),
	(DEFAULT, '¿', 191),
	(DEFAULT, '?', 63),
	(DEFAULT, '.', 46),
	(DEFAULT, ',', 44),
	(DEFAULT, ':', 58),
	(DEFAULT, ';', 59),
	(DEFAULT, '-', 45),
	(DEFAULT, '(', 40),
	(DEFAULT, ')', 41),
	(DEFAULT, '{', 123),
	(DEFAULT, '}', 125),
	(DEFAULT, '[', 91),
	(DEFAULT, ']', 93),
	(DEFAULT, $$'$$, 39),
	(DEFAULT, '<', 60),
	(DEFAULT, '>', 62),
	(DEFAULT, '+', 43),
	(DEFAULT, '*', 42),
	(DEFAULT, '/', 47),
	(DEFAULT, '=', 61),
	(DEFAULT, '#', 35),
	(DEFAULT, '@', 64),
	(DEFAULT, '%', 37),
	(DEFAULT, '$', 36),
	(DEFAULT, '&', 38);

