Statistics Class Reference
#include <Statistics.hpp>
Detailed Description
Statistics about the text recognition process.
This class stores a number of statistical data regarding the elapsed time during the text recognition process, accumulated internally mostly in algorithms.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-08
Definition at line 19 of file Statistics.hpp.
Public Member Functions
Statistics ()
Constructor.
Statistics operator+ (const Statistics &statistics) const
Allows the sum of two different statistics.
Statistics operator- (const Statistics &statistics) const
Allows the subtraction of two different statistics.
const double & backgroundReferenceGrayLevelFindingTime () const
Returns the elapsed time in the reference gray level of the background finding algorithm.
const double & optimalThresholdComputingTime () const
Returns the elapsed time in the optimal threshold computing algorithm.
const double & noiseRemovalTime () const
Returns the elapsed time in the noise removal algorithm.
const double & preprocessingTime () const
Returns the total elapsed time within the preprocessing stage.
const double & thresholdingTime () const
Returns the elapsed time while applying the thresholding algorithm.
const double & shapesFindingTime () const
Returns the elapsed time while finding the shapes in a clip.
const double & segmentationTime () const
Returns the total elapsed time within the segmentation stage.
Private Member Functions
void backgroundReferenceGrayLevelFindingTime (const double &time)
Sets the elapsed time in the reference gray level of the background finding algorithm.
void optimalThresholdComputingTime (const double &time)
Sets the elapsed time in the optimal threshold computing algorithm.
void noiseRemovalTime (const double &time)
Sets the elapsed time in the noise removal algorithm.
void thresholdingTime (const double &time)
Sets the elapsed time in the thresholding algorithm.
void shapesFindingTime (const double &time)
Sets the elapsed time in the shapes finding algorithm.
Private Attributes
double backgroundReferenceGrayLevelFindingTime_
Elapsed time in the reference gray level of the background finding algorithm.
double optimalThresholdComputingTime_
Elapsed time in the optimal threshold computing algorithm.
double noiseRemovalTime_
Elapsed time in the noise removal algorithm.
double preprocessingTime_
Total elapsed time within the preprocessing stage.
double thresholdingTime_
Elapsed time while applying the thresholding algorithm.
double shapesFindingTime_
Elapsed time while finding the shapes in a clip.
double segmentationTime_
Total elapsed time within the segmentation stage.
Friends
class Recognizer
Declares the class Recognizer as friend.
Constructor & Destructor Documentation
Statistics::Statistics ()
Constructor.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-04
Initializes a Statistics object with timers set to 0.0
Definition at line 12 of file Statistics.cpp.
Member Function Documentation
Statistics Statistics::operator+ (const Statistics & statistics) const [inline]
Allows the sum of two different statistics.
Parameters:
statistics A set of statistical data as the second operand
Returns: A new set of statistical data as a result of summing the time parameters of both objects each other
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-22
Definition at line 241 of file Statistics.hpp.
Statistics Statistics::operator- (const Statistics & statistics) const [inline]
Allows the subtraction of two different statistics.
Parameters:
statistics A set of statistical data as the second operand
Returns: A new set of statistical data as a result of subtracting the time parameters of both objects each other
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-22
Definition at line 260 of file Statistics.hpp.
const double & Statistics::backgroundReferenceGrayLevelFindingTime () const [inline]
Returns the elapsed time in the reference gray level of the background finding algorithm.
Returns: Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 279 of file Statistics.hpp.
Referenced by main(), and Recognizer::obtainText().
const double & Statistics::optimalThresholdComputingTime () const [inline]
Returns the elapsed time in the optimal threshold computing algorithm.
Returns: Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 288 of file Statistics.hpp.
Referenced by main(), and Recognizer::obtainText().
const double & Statistics::noiseRemovalTime () const [inline]
Returns the elapsed time in the noise removal algorithm.
Returns: Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 297 of file Statistics.hpp.
Referenced by main(), and Recognizer::obtainText().
const double & Statistics::preprocessingTime () const [inline]
Returns the total elapsed time within the preprocessing stage.
Returns: Total elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 306 of file Statistics.hpp.
Referenced by main().
const double & Statistics::thresholdingTime () const [inline]
Returns the elapsed time while applying the thresholding algorithm.
Returns: Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 315 of file Statistics.hpp.
Referenced by main(), and Recognizer::obtainText().
const double & Statistics::shapesFindingTime () const [inline]
Returns the elapsed time while finding the shapes in a clip.
Returns: Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 324 of file Statistics.hpp.
Referenced by main(), and Recognizer::obtainText().
const double & Statistics::segmentationTime () const [inline]
Returns the total elapsed time within the segmentation stage.
Returns: Total elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 333 of file Statistics.hpp.
Referenced by main().
void Statistics::backgroundReferenceGrayLevelFindingTime (const double & time) [private]
Sets the elapsed time in the reference gray level of the background finding algorithm.
Parameters:
time Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-06
Definition at line 25 of file Statistics.cpp.
void Statistics::optimalThresholdComputingTime (const double & time) [private]
Sets the elapsed time in the optimal threshold computing algorithm.
Parameters:
time Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-06
Definition at line 36 of file Statistics.cpp.
void Statistics::noiseRemovalTime (const double & time) [private]
Sets the elapsed time in the noise removal algorithm.
Parameters:
time Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-06
Definition at line 47 of file Statistics.cpp.
void Statistics::thresholdingTime (const double & time) [private]
Sets the elapsed time in the thresholding algorithm.
Parameters:
time Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 58 of file Statistics.cpp.
void Statistics::shapesFindingTime (const double & time) [private]
Sets the elapsed time in the shapes finding algorithm.
Parameters:
time Elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 69 of file Statistics.cpp.
The documentation for this class was generated from the following files:
Statistics.hpp (154)
Statistics.cpp (153)