Text Class Reference
#include <Text.h>
Detailed Description
Text extracted from the clip by the recognizer.
This class stores the text que has been extracted from the press-clip during the recognition process. Besides the text itself, it also keeps some extra information: appearance rate of every word, font style of every character and the font proportionality, among others.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 30 of file Text.h.
Public Member Functions
Text ()
Constructor.
Text (string content)
Constructor.
Text (string content, vector< Style > styles)
Constructor.
~Text ()
Destructor.
void addCharacter (char character)
Adds a character to the text.
void addCharacter (char character, Style style)
Adds a character to the text.
void addCharacter (char character, unsigned int position)
Adds a character to the text.
void addCharacter (char character, Style style, unsigned int position)
Adds a character to the text.
void removeCharacter (unsigned int position)
Removes a character from the text.
Style getCharacterStyle (unsigned int position) const
Returns the style of a single character.
void setCharacterStyle (unsigned int position, Style style)
Sets the style of a single character.
string content () const
Returns the text itself.
void content (string content)
Sets the text.
vector< Style > styles () const
Returns the list of text styles.
void styles (vector< Style > styles)
Sets the list of text styles.
unsigned int length () const
Returns the text length.
vector< WordRate > wordRates () const
Returns the appearance rates of every single word in text.
FontProportionality proportionality () const
Returns the font proportionality in text.
void proportionality (FontProportionality proportionality)
Sets the font proportionality in text.
Private Member Functions
void computeWordRates ()
Builds the vector with every word appearance rate.
void updateWordRate (string word_)
Increases by one the number of appearances of a word.
void tokenize (vector< string > &tokens_, const string &delimiters_=` ,.\n\t:;!¡¿?&/()=`) const
Extracts the words surrounded by default delimiters from text.
Private Attributes
string content_
The text itself.
vector< Style > styles_
A list of every character style.
FontProportionality proportionality_
The text proportionality.
vector< WordRate > wordRates_
A list of appearance rates of every single word in text.
Constructor & Destructor Documentation
Text::Text ()
Constructor.
Initializes a Text object with empty content and no styles
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-23
Definition at line 15 of file Text.cpp.
Text::Text (string content)
Constructor.
Initializes a Text object with the content passed in content_ and no styles
Parameters:
content Initial text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-23
Definition at line 30 of file Text.cpp.
Text::Text (string content, vector< Style > styles)
Constructor.
Initializes a Text object with the content passed in content_ and styles passed in styles_
Parameters:
content Initial text
styles Style of every character in text
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-23
Definition at line 51 of file Text.cpp.
Text::~Text ()
Destructor.
Destroys a Text object
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-18
Definition at line 64 of file Text.cpp.
Member Function Documentation
void Text::addCharacter (char character)
Adds a character to the text.
The character passed is appended to the end of the text with a default style.
Parameters:
character Character to add
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 176 of file Text.cpp.
Referenced by addCharacter().
void Text::addCharacter (char character, Style style)
Adds a character to the text.
The character is appended to the end of the text with the style passed.
Parameters:
character Character to add
style Style of the character
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 161 of file Text.cpp.
void Text::addCharacter (char character, unsigned int position)
Adds a character to the text.
The character is appended to the text at position passed, with a default style. If the position passed is over the text total length, the character is appended to the end of the text.
Parameters:
character Character to add
position Position where adding the character to
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 137 of file Text.cpp.
void Text::addCharacter (char character, Style style, unsigned int position)
Adds a character to the text.
The character is appended to the text at position passed in position_, and with style passed in style_. If no position is passed, the character is appended to the end. Similarly, if no style is passed a default style is assigned to the character. If the position passed is over the text total length, the character is appended to the end of the text.
Parameters:
character Character to add
style Style of the character
position Position where adding the character to
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-23
Definition at line 86 of file Text.cpp.
void Text::removeCharacter (unsigned int position)
Removes a character from the text.
The character is removed from the position in text passed in position_, unless it is over the text total length. In such case, the last character is removed
Parameters:
position Position where removing the character from
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-23
Definition at line 192 of file Text.cpp.
Style Text::getCharacterStyle (unsigned int position) const
Returns the style of a single character.
The style of a character at position passed is return unless the position will be over the text length. In this case an empty style is returned.
Parameters:
position Position where getting the character style from
Returns: The style of the character
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 236 of file Text.cpp.
void Text::setCharacterStyle (unsigned int position, Style style)
Sets the style of a single character.
The character at position position_ in text is set with the style passed. If the position passed in position_ is over the text total length no changes are made.
Parameters:
position Position of the character whose style is going to be modify
style New style for the character
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 257 of file Text.cpp.
string Text::content () const
Returns the text itself.
Returns: The content of the text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 270 of file Text.cpp.
void Text::content (string content)
Sets the text.
Parameters:
content The content of the text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 282 of file Text.cpp.
vector< Style > Text::styles () const
Returns the list of text styles.
Returns: styles A vector with the styles of every character in text
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 300 of file Text.cpp.
void Text::styles (vector< Style > styles)
Sets the list of text styles.
Parameters:
styles A vector with the styles of every character in text
See also: Style
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 314 of file Text.cpp.
unsigned int Text::length () const
Returns the text length.
Returns: The length of the text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 326 of file Text.cpp.
Referenced by addCharacter(), getCharacterStyle(), removeCharacter(), and setCharacterStyle().
vector< WordRate > Text::wordRates () const
Returns the appearance rates of every single word in text.
Returns: A vector with every different word and their appearance rate
See also: WordRate
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 340 of file Text.cpp.
Referenced by updateWordRate().
FontProportionality Text::proportionality () const
Returns the font proportionality in text.
The proportionality may be monospaced or proportional
Returns: Proportionality of the text according to values in FontProportionality
See also: FontProportionality
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 356 of file Text.cpp.
void Text::proportionality (FontProportionality proportionality)
Sets the font proportionality in text.
Parameters:
proportionality Proportionality of text
See also: FontProportionality
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 370 of file Text.cpp.
void Text::computeWordRates () [private]
Builds the vector with every word appearance rate.
This method must be called every time the content changes, since there is no public method for a class user to make it by itself. By the way, the number of words in text is also computed.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 409 of file Text.cpp.
Referenced by addCharacter(), content(), removeCharacter(), and Text().
void Text::updateWordRate (string word) [private]
Increases by one the number of appearances of a word.
Parameters:
word Word whose appearance rate must be update
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-22
Definition at line 382 of file Text.cpp.
Referenced by computeWordRates().
void Text::tokenize (vector< string > & tokens, const string & delimiters = ` ,.\n\t:;!¡¿?&/()=`) const [private]
Extracts the words surrounded by default delimiters from text.
Parameters:
$\rightarrow$ tokens Vector where storing the words found to
delimiters Characters that may delimiter a valid word
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-22
Definition at line 433 of file Text.cpp.
Referenced by computeWordRates().
The documentation for this class was generated from the following files:
Text.h (116)
Text.cpp (117)