Preprocessor Class Reference
#include <Preprocessor.hpp>
Detailed Description
Preprocessor of the OCR process.
This class encapsulates all the methods related to preprocessing stage. Its task is to enhance the image quality by applying some techniques of image preprocessing theory and compute a number of parameters such as the optimal thresolding value or the background reference gray level
See also: Clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-11
Definition at line 25 of file Preprocessor.hpp.
Public Member Functions
Preprocessor ()
Constructor.
const unsigned char & optimalThreshold () const
Returns the optimal threshold found in the last clip used.
void optimalThreshold (const unsigned char &threshold)
Sets the optimal threshold to use in algorithms.
const unsigned char & backgroundReferenceGrayLevel () const
Returns the background reference gray level in the last clip used.
const double & noiseRemovalTime () const
Returns the elapsed time while applying the 'isolated noise removal' algorithm.
const double & optimalThresholdComputingTime () const
Returns the elapsed time while founding the optimal threshold within the clip.
const double & backgroundReferenceGrayLevelFindingTime () const
Returns the elapsed time while computing the background reference gray level within the clip.
const unsigned char & computeOptimalThreshold (const Clip &clip, const unsigned int &technique=0)
Computes the optimal threshold value within a clip.
const unsigned char & findBackgroundReferenceGrayLevel (const Clip &clip, const unsigned int &referenceGrayLevelNeighbours=2)
Computes the background reference gray level value within a clip.
void removeIsolatedNoise (Clip &clip, const unsigned int &isolationCoefficient=0)
Applies the 'isolated noise removal' algorithm.
Private Member Functions
void computeSonkaOptimalThreshold (const Clip &clip)
Implementation of optimal threshold computing following the Sonka's technique.
void computeOtsuOptimalThreshold (const Clip &clip)
Implementation of optimal threshold computing following the Otsu's technique.
Private Attributes
unsigned char optimalThreshold_
Optimal threshold value within the clip.
unsigned char backgroundReferenceGrayLevel_
Background reference gray level.
double noiseRemovalTime_
Elapsed time when applying the 'isolated noise removal' algorithm.
double optimalThresholdComputingTime_
Elapsed time when converting the image to a grayscale colorspace.
double backgroundReferenceGrayLevelFindingTime_
Elapsed time when computing the background gray level.
Constructor & Destructor Documentation
Preprocessor::Preprocessor ()
Constructor.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-08
Initializes a Preprocessor object
Definition at line 20 of file Preprocessor.cpp.
Member Function Documentation
const unsigned char & Preprocessor::optimalThreshold () const [inline]
Returns the optimal threshold found in the last clip used.
Returns: Current optimal threshold computed from the last clip used
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 233 of file Preprocessor.hpp.
Referenced by Recognizer::obtainText().
void Preprocessor::optimalThreshold (const unsigned char & threshold) [inline]
Sets the optimal threshold to use in algorithms.
Parameters:
threshold A value between 0 and 255 that stablishes the optimal threshold of a clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-08
Definition at line 242 of file Preprocessor.hpp.
const unsigned char & Preprocessor::backgroundReferenceGrayLevel () const [inline]
Returns the background reference gray level in the last clip used.
Returns: Reference background gray level in the last clip used
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 251 of file Preprocessor.hpp.
Referenced by Recognizer::obtainText().
const double & Preprocessor::noiseRemovalTime () const [inline]
Returns the elapsed time while applying the 'isolated noise removal' algorithm.
Returns: Elapsed time when applying the 'isolated noise removal' algorithm
See also: removeIsolatedNoise()
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 260 of file Preprocessor.hpp.
Referenced by Recognizer::obtainText().
const double & Preprocessor::optimalThresholdComputingTime () const [inline]
Returns the elapsed time while founding the optimal threshold within the clip.
Returns: Elapsed time while founding the optimal threshold within the clip
See also: computeOptimalThreshold()
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 269 of file Preprocessor.hpp.
Referenced by Recognizer::obtainText().
const double & Preprocessor::backgroundReferenceGrayLevelFindingTime () const [inline]
Returns the elapsed time while computing the background reference gray level within the clip.
Returns: Elapsed time while computing the background reference gray level
See also: findBackgroundReferenceGrayLevel()
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 278 of file Preprocessor.hpp.
Referenced by Recognizer::obtainText().
const unsigned char & Preprocessor::computeOptimalThreshold (const Clip & clip, const unsigned int & technique = 0)
Computes the optimal threshold value within a clip.
Precondition: You MUST call findBackgroundReferenceGrayLevel() method before calling this one, since it sets internal attributes.
Postcondition: The member optimalThresholdComputingTime_ is modified.
Parameters:
clip The clip where applying the algorithm over
technique An integer that tells the technique that must be used: 0 for Sonka's method or 1 for Otsu's method.
See also: Clip, computeSonkaOptimalThreshold(), computeOtsuOptimalThreshold()
Returns: The optimal threshold of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
To compute the optimal threshold we may follow two different strategies. The Sonka's method is faster but sometimes less accurate, while Otsu's method is more accurate but slower and sometimes does not perform well if there are more than three representative gray levels. Unless you are testing both algorithms or have specific domain knowledge we strongly recommend the Sonka's technique.
Definition at line 33 of file Preprocessor.cpp.
Referenced by Recognizer::obtainText().
const unsigned char & Preprocessor::findBackgroundReferenceGrayLevel (const Clip & clip, const unsigned int & referenceGrayLevelNeighbours = 2)
Computes the background reference gray level value within a clip.
Postcondition: The member backgroundReferenceGrayLevelFindingTime_ is modified.
Parameters:
clip The clip where applying the algorithm over
referenceGrayLevelNeighbours Number of neighbours of the more frequent gray level to explore on each direction
See also: Clip
Returns: The reference gray level of the background
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
To find the reference gray level of the background it is assumed that there are more pixels belonging to the background than belonging to the foreground. Then, we search the more frequent gray level and its neighbours. Finally, we compute a gray level weighted mean using all those values.
Bug There are cases where the reference gray level found does not match with the real background gray level, because the assumption made about the background's number of pixels is false. An alternative may be to find two reference gray levels; if the classification process does not work, everything must be undone and start again with the second reference gray level.
Definition at line 53 of file Preprocessor.cpp.
Referenced by Recognizer::obtainText().
void Preprocessor::removeIsolatedNoise (Clip & clip, const unsigned int & isolationCoefficient = 0)
Applies the 'isolated noise removal' algorithm.
Precondition: You MUST call computeOptimalThreshold() and findBackgroundReferenceGrayLevel() methods before calling this one, since they set internal attributes.
Postcondition: The clip may be modified if any noise is found.
Parameters:
$\leftrightarrow$ clip The clip where applying the algorithm over
isolationCoefficient The maximum noisy neighbours for a pixel to consider it as isolated
See also: Clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-11
The 'isolated noise removal' algorithm tries to eliminate isolated noisy pixels from an clip. The isolationCoefficient parameter defines how much isolated should be a noisy pixel to be removed. That means a noisy pixel will be removed whenever it has as much neighbours whose gray level is over a threshold value as isolationCoefficient.
Definition at line 129 of file Preprocessor.cpp.
Referenced by Recognizer::obtainText().
void Preprocessor::computeSonkaOptimalThreshold (const Clip & clip) [private]
Implementation of optimal threshold computing following the Sonka's technique.
Parameters:
clip The clip where applying the algorithm over
See also: Clip
Postcondition: The attribute optimalThreshold_ is initialized to the threshold found
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-14
The strategy proposed by M. Sonka, V. Hlavac and R. Boyle in `Image Processing, Analysis and Machine Vision` (Thomson Learning, 2008) is to find a mean value between the mean value of background's gray level and the mean value of objects' gray level, starting from an initial threshold value that is given by the member backgroundReferenceGrayLevel_.
Definition at line 199 of file Preprocessor.cpp.
Referenced by computeOptimalThreshold().
void Preprocessor::computeOtsuOptimalThreshold (const Clip & clip) [private]
Implementation of optimal threshold computing following the Otsu's technique.
Parameters:
clip The clip where applying the algorithm over
See also: Clip
Postcondition: The attribute optimalThreshold_ is initialized to the threshold found
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-14
The strategy proposed by N. Otsu in `A Threshold Selection Method from Gray-Level Histograms` (IEEE Transactions on Systems, Man, and Cybernetics, 1979) maximises the likelihood that the threshold is chosen so as to split the image between and object and its background. An optimal threshold is selected by the discriminant criterion, namely, so as to maximize the separability of the resultant classes in gray levels. The procedure is very simple, utilizing only the zeroth- and the first-order cumulative moments of the gray-level histogram.
1. Compute the gray-level histogram and normalized it.
2. Compute the total mean level of the image $\mu_T$.
3. For each gray level $k$ compute $\omega(k)$ y $\mu(k)$, which are the zeroth- and the first-order cumulative moments of the histogram up to the $k$th level.
4. Compute the variance of the class separability $\sigma_B^2(k)$.
5. Find the $k$th level that makes a $\sigma_B^2(k)$ value the maximum.
Definition at line 256 of file Preprocessor.cpp.
Referenced by computeOptimalThreshold().
The documentation for this class was generated from the following files:
Preprocessor.hpp (148)
Preprocessor.cpp (149)