Clip Class Reference
#include <Clip.h>
Detailed Description
Press clip where the recognizer has to extract the text from.
This class manages the press clip where the recognizer has to extract the text, loading it with the Magick++ utilities. The press clip is an image that may come in several formats, such JPEG, PDF, PNG, etc. The ImageMagick library provides an abstraction layer to keep the code independent from the format.
The idea behind this class is to encapsulate all the interactions with the Magick++ API, so that the rest of the classes have a unified way to work with the original image.
See also: Pixel, Colorspace
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-29
Definition at line 37 of file Clip.h.
Public Member Functions
Clip (Image image, unsigned int xOrigin, unsigned int yOrigin, unsigned int height, unsigned int width)
Constructor.
~Clip ()
Destructor.
Image image ()
Returns the current Image object.
unsigned int xOrigin () const
Returns the X coordinate of the clip's upper leftmost pixel.
void xOrigin (unsigned int x)
Sets the X coordinate of the clip's upper leftmost pixel.
unsigned int yOrigin () const
Returns the Y coordinate of the clip's upper leftmost pixel.
void yOrigin (unsigned int y)
Sets the Y coordinate of the clip's upper leftmost pixel.
unsigned int height () const
Returns the clip's height.
void height (unsigned int height)
Sets the clip's height.
unsigned int width () const
Returns the clip's width.
void width (unsigned int width)
Sets the clip's width.
Colorspace colorspace () const
Returns the clip's current colorspace.
void colorspace (Colorspace colorspace)
Sets the clip's current colorspace.
bool isGrayscale () const
Returns true if the clip is in grayscale.
bool isColor () const
Returns true if the clip is in color.
bool isMonochromatic () const
Returns true if the clips is in black and white.
Pixel getPixel (unsigned int x, unsigned int y) const
Returns the pixel at coordinates (x,y).
void setPixel (unsigned int x, unsigned int y, double grayLevel)
Sets the gray level of a pixel at coordinates (x,y).
void setPixel (unsigned int x, unsigned int y, double red, double green, double blue)
Sets the color of a pixel at coordinates (x,y).
void setPixel (unsigned int x, unsigned int y, bool isForeground)
Sets whether a pixel at coordinates (x,y) belongs to the foreground or not.
Private Member Functions
void relocateClipOrigin ()
Relocates the origin of the clip.
void adjustClipSize ()
Adjusts the size of the clip.
Private Attributes
Image image_
Image where the clip belongs to.
unsigned int xOrigin_
X coordinate of the clip's upper leftmost pixel.
unsigned int yOrigin_
Y coordinate of the clip's upper leftmost pixel.
unsigned int height_
Height of the clip in pixels.
unsigned int width_
Width of the clip in pixels.
Colorspace colorspace_
Clip's colorspace.
Pixels * frame_
Pixels frame where the clip is located.
PixelPacket * originPixel_
Frame's upper leftmost pixel.
Constructor & Destructor Documentation
Clip::Clip (Image image, unsigned int xOrigin, unsigned int yOrigin, unsigned int height, unsigned int width)
Constructor.
Initializes a Clip object located at coordinates (xOrigin,yOrigin) in the source image, with the height and width passed. The xOrigin value allows access to the image rows, while the yOrigin value allows access to the image columns. If the xOrigin and yOrigin are out of the image borders, an exception is thrown. If the width and height are over the image borders the clip is truncated. Note that, as in C and C++, indexes begin at (0,0).
Parameters:
image The underlying image where the clip belongs to
xOrigin The upper left-most pixel X coordinate of the clip
yOrigin The upper left-most pixel Y coordinate of the clip
height The height of the clip
width The width of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-01
Definition at line 24 of file Clip.cpp.
Clip::~Clip ()
Destructor.
Destroys a Clip object, deleting all the associated data from Magick++ API
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 106 of file Clip.cpp.
Member Function Documentation
Image Clip::image ()
Returns the current Image object.
Returns: The underlying image where the clip belongs to
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 118 of file Clip.cpp.
unsigned int Clip::xOrigin () const
Returns the X coordinate of the clip's upper leftmost pixel.
Returns: The upper left-most pixel X coordinate of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 130 of file Clip.cpp.
void Clip::xOrigin (unsigned int x)
Sets the X coordinate of the clip's upper leftmost pixel.
If the new value x is over the image borders, an exception is thrown.
Parameters:
x The upper left-most pixel X coordinate of the clip
Exceptions:
NessieException
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 146 of file Clip.cpp.
unsigned int Clip::yOrigin () const
Returns the Y coordinate of the clip's upper leftmost pixel.
Returns: The upper left-most pixel Y coordinate of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 164 of file Clip.cpp.
void Clip::yOrigin (unsigned int y)
Sets the Y coordinate of the clip's upper leftmost pixel.
If the new value y is over the image borders, an exception is thrown.
Parameters:
y The upper left-most pixel Y coordinate of the clip
Exceptions:
NessieException
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 180 of file Clip.cpp.
unsigned int Clip::height () const
Returns the clip's height.
Returns: The height of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 198 of file Clip.cpp.
Referenced by Preprocessor::findBackgroundReferenceGrayLevel(), and Preprocessor::removeIsolatedNoise().
void Clip::height (unsigned int height)
Sets the clip's height.
If the height is over the image borders the clip is truncated to its maximum allowed value.
Parameters:
height The height of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-01
Definition at line 212 of file Clip.cpp.
unsigned int Clip::width () const
Returns the clip's width.
Returns: The width of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 229 of file Clip.cpp.
Referenced by Preprocessor::findBackgroundReferenceGrayLevel(), and Preprocessor::removeIsolatedNoise().
void Clip::width (unsigned int width)
Sets the clip's width.
If the width is over the image borders the clip is truncated to its maximum allowed value.
Parameters:
width The height of the clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-01
Definition at line 243 of file Clip.cpp.
Colorspace Clip::colorspace () const
Returns the clip's current colorspace.
Returns: The current colorspace of the clip
See also: Colorspace
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-24
Definition at line 262 of file Clip.cpp.
Referenced by Preprocessor::convertToGrayscale().
void Clip::colorspace (Colorspace colorspace)
Sets the clip's current colorspace.
By setting the colorspace to a certain value the image colorspace changes, affecting all its pixels and the information regarding the image colors.
Parameters:
colorspace The colorspace of the clip according to values in Colorspace
See also: Colorspace
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 279 of file Clip.cpp.
bool Clip::isGrayscale () const
Returns true if the clip is in grayscale.
Returns: True if the colorspace of the clip is grayscale
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 331 of file Clip.cpp.
bool Clip::isColor () const
Returns true if the clip is in color.
Returns: True if the colorspace of the clip is RGB
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 346 of file Clip.cpp.
bool Clip::isMonochromatic () const
Returns true if the clips is in black and white.
Returns: True if the colorspace of the clip is monochromatic
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 361 of file Clip.cpp.
Pixel Clip::getPixel (unsigned int x, unsigned int y) const
Returns the pixel at coordinates (x,y).
If either the x coordinate or the y coordinate are out of the image borders, an exception is thrown. If the image colorspace is undefined, an exception is also thrown.
Parameters:
x The upper left-most pixel X coordinate of the clip
y The upper left-most pixel Y coordinate of the clip
Returns: The pixel at coordinates (x,y)
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-02
Definition at line 382 of file Clip.cpp.
Referenced by Preprocessor::findBackgroundReferenceGrayLevel(), and Preprocessor::removeIsolatedNoise().
void Clip::setPixel (unsigned int x, unsigned int y, double grayLevel)
Sets the gray level of a pixel at coordinates (x,y).
If either the x coordinate or the y coordinate are out of the image borders, an exception is thrown. If the image colorspace is not grayscale no changes are made. The gray level must be normalized in a value from 0 to 1, otherwise it is truncated either to 0 if it's less than 0 or to 1 if it's greater than 1.
Parameters:
x The upper left-most pixel X coordinate of the clip
y The upper left-most pixel Y coordinate of the clip
grayLevel The new gray level for the pixel at coordinates (x,y)
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-02-10
Definition at line 436 of file Clip.cpp.
Referenced by Preprocessor::removeIsolatedNoise().
void Clip::setPixel (unsigned int x, unsigned int y, double red, double green, double blue)
Sets the color of a pixel at coordinates (x,y).
If either the x coordinate or the y coordinate are out of the image borders, an exception is thrown. If the image colorspace is not RGB no changes are made. Each channel value must be normalized in a value from 0 to 1, otherwise it is truncated either to 0 if it's less than 0 or to 1 if it's greater than 1.
Parameters:
x The upper left-most pixel X coordinate of the clip
y The upper left-most pixel Y coordinate of the clip
red The new color value of red channel for the pixel at coordinates (x,y)
green The new color value of green channel for the pixel at coordinates (x,y)
blue The new color value of blue channel for the pixel at coordinates (x,y)
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 484 of file Clip.cpp.
void Clip::setPixel (unsigned int x, unsigned int y, bool isForeground)
Sets whether a pixel at coordinates (x,y) belongs to the foreground or not.
If either the x coordinate or the y coordinate are out of the image borders, an exception is thrown. If the image colorspace is not monochromatic no changes are made
Parameters:
x The upper left-most pixel X coordinate of the clip
y The upper left-most pixel Y coordinate of the clip
isForeground Tells whether the pixel at coordinates (x,y) belongs to the foreground or not
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 529 of file Clip.cpp.
void Clip::relocateClipOrigin () [private]
Relocates the origin of the clip.
When any of the clip attributes change, it is neccesary to relocate the clip position over the source image
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 569 of file Clip.cpp.
Referenced by height(), width(), xOrigin(), and yOrigin().
void Clip::adjustClipSize () [private]
Adjusts the size of the clip.
When the clip origin changes, it is neccesary to test whether the clip dimensions fall out of the underlying image or not
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-09-26
Definition at line 590 of file Clip.cpp.
Referenced by xOrigin(), and yOrigin().
Field Documentation
Colorspace Clip::colorspace_ [private]
Clip's colorspace.
It is modified automatically when the clip's image source changes
Definition at line 169 of file Clip.h.
Referenced by Clip(), colorspace(), getPixel(), isColor(), isGrayscale(), isMonochromatic(), and setPixel().
Pixels* Clip::frame_ [private]
Pixels frame where the clip is located.
It is modified automatically when the clip attributes change
Definition at line 174 of file Clip.h.
Referenced by Clip(), colorspace(), relocateClipOrigin(), setPixel(), and ~Clip().
PixelPacket* Clip::originPixel_ [private]
Frame's upper leftmost pixel.
It is modified automatically when information about the clip attributes change
Definition at line 179 of file Clip.h.
Referenced by Clip(), getPixel(), relocateClipOrigin(), and setPixel().
The documentation for this class was generated from the following files:
Clip.h (114)
Clip.cpp (117)