Recognizer Class Reference
#include <Recognizer.hpp>
Detailed Description
Manager of the whole OCR process.
This class encapsulates all the stages related to the optical character recognition process of every clip within a newspaper's page. For each image provided (via constructors) representing the page, you can obtain its text and a number of statistics regarding the recognition process performance.
At the moment, this class manages the press clips within an image loaded with the Magick++ utilities. The newspaper pages should be an image that comes in several formats, such JPEG, PDF, PNG, etc. The Magick++ library (an API for the ImageMagick suite) provides an abstraction layer to keep the code independent from the image format. The idea behind this class is to encapsulate all the interactions with Magick++, so that the rest of the classes have an unified way to work.
In future modifications any library may be added to load the images. A developer should overload a loadImage() method, modify the constructor Recognizer(const std::string &path) or add a new constructor with specific parameters, and overload a writeExternalImage() method.
See also: Clip, Text, Statistics, Magick++ API
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-10
Definition at line 42 of file Recognizer.hpp.
Public Member Functions
Recognizer (const std::string &path)
Constructor.
Recognizer (Magick::Image &image)
Constructor.
void obtainText ()
Recognizes the text within the whole page at once.
void obtainText (const std::vector< ClipLocation > &coordinates)
Recognizes the text within multiple press clips whose coordinates are passed.
void obtainText (const unsigned int &x, const unsigned int &y, unsigned int &height, unsigned int &width)
Recognizes the text within a single press clip located at coordinates (x,y).
const Text & text (const unsigned int &label=0) const
Returns the text of a single clip.
const std::vector< Text > & texts () const
Returns the text of every loaded clip.
const Statistics & statistic (const unsigned int &label=0) const
Returns the statistical data regarding the recognition process of a single clip.
const std::vector< Statistics > & statistics () const
Returns the statistical data regarding the recognition process of every loaded clip.
void writeExternalImage (Magick::Image &externalImage) const
Writes the information of the internal data into an external image.
Private Member Functions
void loadImage (Magick::Image &image)
Loads an Image object created with the Magick++ API into the internal data structure.
void updateImage (const Clip &clip)
Writes the information of a clip into the underlying image.
Private Attributes
std::vector< unsigned char > image_
Underlying image where where clip belongs to.
unsigned int height_
Height of the underlying image.
unsigned int width_
Width of the underlying image.
std::vector< Text > texts_
Text obtained after the recognition process.
std::vector< Statistics > statistics_
Statistics gathered during the recognition process.
Constructor & Destructor Documentation
Recognizer::Recognizer (const std::string & path)
Constructor.
Parameters:
path Relative path to the image within the filesystem
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-10
Creates a new Recognizer object loading the image from disk. If the image is multi-frame only the first one is taken, e.g. the first page of a PDF with multiple pages.
Definition at line 21 of file Recognizer.cpp.
Recognizer::Recognizer (Magick::Image & image)
Constructor.
Parameters:
image An Image object from the Magick++ API previously loaded
See also: Image
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-10
Creates a new Recognizer object from an image loaded externally with methods from Magick++ API. If the image is multi-frame only the first one is taken, e.g. the first page of a PDF with multiple pages.
Definition at line 43 of file Recognizer.cpp.
Member Function Documentation
void Recognizer::obtainText ()
Recognizes the text within the whole page at once.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-09
It is assumed that the image is a clip itself we can obtain the text processing the whole image. Since there is only one clip you can gather its text and its statistics by simply calling text() and statistics() with no parameters at all.
Definition at line 59 of file Recognizer.cpp.
Referenced by main(), and obtainText().
void Recognizer::obtainText (const std::vector< ClipLocation > & coordinates)
Recognizes the text within multiple press clips whose coordinates are passed.
Parameters:
coordinates A list of coordinates to locate a number of clips within the page
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Each set of points provides us a clip that can be located within the page.
Definition at line 69 of file Recognizer.cpp.
void Recognizer::obtainText (const unsigned int & x, const unsigned int & y, unsigned int & height, unsigned int & width)
Recognizes the text within a single press clip located at coordinates (x,y).
Parameters:
x Top left-most pixel X coordinate
y Top left-most pixel Y coordinate
height Clip's height
width Clip's width
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
If the clip falls outside the image an exception is thrown unless it can be truncated safety. By default the text extracted and the statistical data regarding the recognition process are saved in the first position of internal data structures. That means you can gather them by simply calling text() and statistics() with no parameters at all.
Definition at line 91 of file Recognizer.cpp.
const Text & Recognizer::text (const unsigned int & label = 0) const [inline]
Returns the text of a single clip.
Parameters:
label A number that tells the clip where the requested text belongs to
See also: Text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 237 of file Recognizer.hpp.
const std::vector< Text > & Recognizer::texts () const [inline]
Returns the text of every loaded clip.
Returns: A list of texts recognized in the clips previously loaded
See also: Text
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 249 of file Recognizer.hpp.
const Statistics & Recognizer::statistic (const unsigned int & label = 0) const [inline]
Returns the statistical data regarding the recognition process of a single clip.
Parameters:
label A number that tells the clip where the requested statistical data belongs to
Returns: Statistical data about the recognition process of a single clip
See also: Statistics
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 258 of file Recognizer.hpp.
Referenced by main().
const std::vector< Statistics > & Recognizer::statistics () const [inline]
Returns the statistical data regarding the recognition process of every loaded clip.
Returns: Statistical data about the recognition process of every clip within the image
See also: Statistics
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Definition at line 270 of file Recognizer.hpp.
void Recognizer::writeExternalImage (Magick::Image & externalImage) const
Writes the information of the internal data into an external image.
Parameters:
externalImage The destination Image object from the Magick++ API previously created
Postcondition: The external image is converted to a grayscale colorspace and its pixels are overwritten according to the information of the internal image
See also: Image
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-10
If either the source or the target are bigger or smaller than its counterpart, only the pixels whose coordinates match are changed.
Definition at line 166 of file Recognizer.cpp.
Referenced by main().
void Recognizer::loadImage (Magick::Image & image) [private]
Loads an Image object created with the Magick++ API into the internal data structure.
Parameters:
image An Image object from the Magick++ API previously created
Postcondition: The internal image is converted to a grayscale colorspace
See also: Image
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-10
The image is automatically converted into a grayscale colorspace according with the RGB values within the original source. If the image comes already in a grayscale colorspace no conversion is applied.
Definition at line 223 of file Recognizer.cpp.
Referenced by Recognizer().
void Recognizer::updateImage (const Clip & clip) [private]
Writes the information of a clip into the underlying image.
Parameters:
clip The clip where the new data is taken
See also: Clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Since the only way of passing a Clip object to this method is invoking Recognizer::obtainText(), and the dimensions are controlled inside that method, here it is assumed that all the coordinates are valid.
Definition at line 258 of file Recognizer.cpp.
Referenced by obtainText().
The documentation for this class was generated from the following files:
Recognizer.hpp (152)
Recognizer.cpp (152)