Segmenter Class Reference
#include <Segmenter.hpp>
Detailed Description
This class encapsulates all the methods related to segmentation stage of the OCR process. Its task is to isolate every shape in a clip that represents a character, storing them in a data structure for further classification.
See also: Clip, Shape, Pixel
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Public Member Functions
Segmenter ()
Constructor.
const unsigned char & inkValue () const
Returns the gray level that represents the ink used in characters.
const std::list< Shape > & shapes () const
Returns the shapes found in the last segmentation process.
const float & thresholdingTime () const
Returns the elapsed time while applying the thresholding algorithm.
const float & shapesFindingTime () const
Returns the elapsed time while finding the shapes.
void applyThreshold (Clip &clip, const unsigned char &threshold, const unsigned char &backgroundReference)
Applies a thresholding algorithm.
void findShapes (const Clip &clip)
Finds a list of isolated shapes in the press clip by joining connected pixels.
Private Types
typedef std::pair< unsigned int, unsigned int > LineMarker
Limits of a line of shapes.
typedef std::list< LineMarker >::iterator LineMarkerIterator
An iterator to a list of LineMarker objects.
typedef std::list< Shape >::iterator ShapeIterator
An iterator to a list of Shape objects.
Private Member Functions
void findSeeds (const Clip &clip)
Find the seeds where the shapes will grow up from.
void growSeedsIntoInitialShapes (const Clip &clip)
Builds a list of shapes founded in a clip by growing seeds into isolated shapes.
void findLineMarkers (const Clip &clip)
Finds the pairs of rows that delimit every line of shapes in a press clip.
void joinVerticallyOverlappedShapes (ShapeIterator &s1, ShapeIterator &s2)
Joins two shapes that are vertically overlapped.
ShapeIterator findVerticallyOverlappedShape (const unsigned int &lineTop, const unsigned int &lineBottom, const ShapeIterator &shape)
Finds a shape that is vertically overlapped to the shape passed, both being in the same line of shapes.
Private Attributes
unsigned char inkValue_
Gray level value of the pixels that have ink.
std::deque< Pixel > seeds_
A list with the coordinates of every pixel that has a gray level equal to inkValue_.
std::deque< bool > visited_
A list of `visited/non visited` status for the pixels in the press clip.
std::list< Shape > shapes_
A list of shapes that represents every character found within the press clip.
std::list< LineMarker > lineMarkers_
A list of integer pairs that defines the limits of every line of characters in a press clip.
float thresholdingTime_
Elapsed time while applying the thresholding algorithm.
float shapesFindingTime_
Elapsed time while applying the shapes finding algorithm.
Member Typedef Documentation
Segmenter::LineMarker [private]
This pair keeps the rows of a press clip that delimits a single line of shapes. The first member representes the row of pixels at the top of the line, while the second member represents the row of pixels at the bottom of the line.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-24
Segmenter::LineMarkerIterator [private]
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-31
Segmenter::ShapeIterator [private]
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-30
Constructor & Destructor Documentation
Segmenter::Segmenter ()
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
Member Function Documentation
const unsigned char & Segmenter::inkValue () const
Returns: A value of 0 or 255
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-18
References inkValue_.
const std::list< Shape > & Segmenter::shapes () const
Returns: A vector of Shape objects
See also: Shape
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
References shapes_.
const float & Segmenter::thresholdingTime () const
Returns: The elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
References thresholdingTime_.
const float & Segmenter::shapesFindingTime () const
Returns: The elapsed time in seconds
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
References shapesFindingTime_.
void Segmenter::applyThreshold (Clip & clip, const unsigned char & threshold, const unsigned char & backgroundReference)
Parameters:
clip A press clip.
threshold A threshold value to differentiate between background and foreground pixels.
backgroundReference Background reference gray level.
Postcondition: Every pixel in the clip has either a gray level of 0 or 255.
The inkValue_ member is initialized to the gray level that represents the ink's gray level of the press clip.
See also: Clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-13
This method implements a simple thresholding algorithm that compares each pixel's gray level with a threshold value. The background reference gray level is taken into account to decide the final gray level that is applied to the pixel, so that the ink value is assumed as the very opposite gray level of background reference.
References Clip::height(), inkValue_, thresholdingTime_, and Clip::width().
void Segmenter::findShapes (const Clip & clip)
Precondition: The clip MUST be thresholded by calling applyThreshold() method before.
Postcondition: The seeds_ member is initialized with the seeds that grew into the shapes.
The visited_ member is initialized with the positions of the seeds set to true.
The shapes_ member is initialized with the shapes that represents character within the clip.
Parameters:
clip The press clip
See also: Clip
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-21
This method isolates every shape in a press clip by connecting pixels of ink that are located together in a 3x3 neighbourhood. The shapes may contain a subset of shapes, since further processing is applied to join accents and other punctuation signs to their characters. The final list of shapes is sorted by lines and columns, so that traversing the list is equivalent to read the text from left to right and from up to down.
References findLineMarkers(), findSeeds(), findVerticallyOverlappedShape(), growSeedsIntoInitialShapes(), joinVerticallyOverlappedShapes(), lineMarkers_, shapes_, and shapesFindingTime_.
void Segmenter::findSeeds (const Clip & clip) [private]
Parameters:
clip The press clip where finding the seeds
Precondition: The press clip must come thresholded in two values, one of them being equal to inkValue_.
Postcondition: seeds_ contains every pixel that has a gray level equal to inkValue_.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-24
A seed is a pixel that has a gray level equal to the gray level of characters in the clip. Thus, the seeds founded by this method are actually all the pixels that do not belong to the background in the clip.
References Clip::height(), inkValue_, seeds_, and Clip::width().
void Segmenter::growSeedsIntoInitialShapes (const Clip & clip) [private]
Parameters:
clip The press clip where the shape will be found from the seeds.
Precondition: seeds_ must be initialized by calling findSeeds() method. Their coordinates must be consistent with the clip dimensions.
Postcondition: shapes_ member contains the initial shapes that represents characters in the clip.
visited_ member is updated by setting to true the position of those pixels that become part of a shape.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-24
The initial shapes are a set of shapes that are inconsistent with the real characters in the press clip. That is because a further processing is necessary to join accents to vocals, split shapes that represents two characters joined, etc.
This method follows a strategy similar to the 'flood fill' algorithm. The main target is to isolate every shape in a clip that represents a character. Every shape is built starting from an ink pixel (a seed) and exploring its neighbourhood looking for connected pixels. The process ends when there are not more seeds to explore and the shapes are completely isolated.
References Clip::height(), inkValue_, seeds_, shapes_, Clip::size(), visited_, and Clip::width().
void Segmenter::findLineMarkers (const Clip & clip) [private]
Parameters:
clip The press clip
Postcondition: The lineMarkers_ member contains pairs of numbers that delimits every isolated line of shapes.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-24
Each row is isolated by searching horizontal blank lines between characters. Every time a row with no pixels of ink is found following a row with some pixels of ink a top marker is set. Then, the following rows are explored until a new blank line is found. The line before that last blank line is set as the bottom marker of the line.
References Clip::height(), lineMarkers_, shapes_, visited_, and Clip::width().
void Segmenter::joinVerticallyOverlappedShapes (ShapeIterator & s1, ShapeIterator & s2) [private]
Parameters:
s1 First shape to join
s2 Second shape to join
Precondition: shapes_ cannot be empty.
Postcondition: A new Shape object is inserted into shapes_ by joining s1 and s2. Both s1 and s2 are then removed from shapes_.
The iterator s1 is updated by pointing to the next shape in shapes_.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-27
References shapes_.
Segmenter::ShapeIterator Segmenter::findVerticallyOverlappedShape (const unsigned int & lineTop, const unsigned int & lineBottom, const ShapeIterator & shape) [private]
Parameters:
lineTop Row that delimits the top of the line
lineBottom Column that delimits the bottom of the line
shape Shape for which a vertically overlapped shape has to be found
Precondition: shapes_ cannot be empty.
Returns: If found, an iterator to a shape that is vertically overlapped to the shape passed. Otherwise, an iterator to the shape passed.
Author: Eliezer Talón (elitalon@gmail.com)
Date: 2008-10-30
The list of shapes is traversed in order to find a shape that is vertically overlapped with the shape passed. A shape is considered as overlapped when at least one pixel is overlapped with the shape of interest. This minimum criteria is necessary because of characters that are too small.
References shapes_.